In [1]:
rohit=[105,203,1]

In [2]:
import numpy as np

In [3]:
np_scores=np.array(rohit)

In [4]:
type(np_scores)

numpy.ndarray

In [5]:
[True,1,2]+[3,4,False]

[True, 1, 2, 3, 4, False]

In [6]:
np.array([True,1,2])+np.array([3,4,False])

array([4, 5, 2])

In [7]:
np.array([True,1,2])*5

array([ 5,  5, 10])

In [8]:
np.array(["Akshay"])+np.array("Patel")

TypeError: ufunc 'add' did not contain a loop with signature matching types dtype('<U6') dtype('<U6') dtype('<U6')

In [10]:
[1,1,1].index(1)

0

In [11]:
np.array([1.0,1,2])

array([1., 1., 2.])

In [13]:
testcric=[
    [180,78],
    [215,102],
    [210,98],
    [188,75]
]

In [14]:
np_test=np.array(testcric)

In [16]:
np_test.shape

(4, 2)

In [17]:
np_test.ndim

2

In [19]:
np_test[0][1]

78

In [23]:
np_test[:,1]

array([ 78, 102,  98,  75])